[package]
name = "rusk-vm"
version.workspace = true
edition.workspace = true

[dependencies]
rusk-bytecode = { path = "../rusk-bytecode" }
rusk-gc = { path = "../rusk-gc" }
rusk-mir = { path = "../rusk-mir" }
