[workspace]
members = [
    "crates/rusk-mir",
    "crates/rusk-compiler",
    "crates/rusk-interpreter",
]

[package]
name = "rusk"
version = "0.1.0"
edition = "2024"

[dependencies]
rusk-compiler = { path = "crates/rusk-compiler" }
rusk-interpreter = { path = "crates/rusk-interpreter" }

[dev-dependencies]
rusk-mir = { path = "crates/rusk-mir" }
