[package]
name = "rusk-host"
version.workspace = true
edition.workspace = true

[dependencies]
rusk-compiler = { path = "../rusk-compiler" }
rusk-bytecode = { path = "../rusk-bytecode" }
rusk-vm = { path = "../rusk-vm" }
